version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PORT=3306
      - MYSQL_DB=real_time_chat_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=your_password
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
      - MYSQL_DATABASE=real_time_chat_db
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data: 